title: <p align="center"> Richa Srivastava </p>
logo: /assets/img/Richa-image.png

description:
  <p align="center">|
  <a href="http://www.linkedin.com/in/richa-shrivastava-b4014739/">LinkedIn</a> |
  <a href="https://github.com/richas78">GitHub</a>
  
  <br>   
  I'm starting working  on Data analysis of my project.
  Worked with FIS in Payment domain from 9+ years
 
  <br>
  </p>



theme: jekyll-theme-minimal
